name: Deploy Function App (Node)

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (api)
        working-directory: api
        run: npm install --omit=dev

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: aqfa   # <--Function App name
          package: 'api'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
