name: Build & Upload Frontend (Static Website)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        working-directory: frontend
        run: |
          npm install
          echo "VITE_API_BASE=${{ secrets.API_BASE_URL }}" >> .env
          npm run build

      - name: Upload to Azure Storage Static Website
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --destination '$web' \
              --source frontend/dist \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key  ${{ secrets.AZURE_STORAGE_KEY }} \
              --overwrite
